# -*- coding: utf-8 -*-
"""diffusion_policy_state_pusht_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxdkgRVfM55zihY9TFLja97cSVZOZq2B
"""

#@markdown ### **Installing pip packages**
#@markdown - Diffusion Model: [PyTorch](https://pytorch.org) & [HuggingFace diffusers](https://huggingface.co/docs/diffusers/index)
#@markdown - Dataset Loading: [Zarr](https://zarr.readthedocs.io/en/stable/) & numcodecs
#@markdown - Push-T Env: gym, pygame, pymunk & shapely
# !python --version
# !pip3 install torch==1.13.1 torchvision==0.14.1 diffusers==0.18.2 \
# scikit-image==0.19.3 scikit-video==1.1.11 zarr==2.12.0 numcodecs==0.10.2 \
# pygame==2.1.2 pymunk==6.2.1 gym==0.26.2 shapely==1.8.4 \
# &> /dev/null # mute output

#@markdown ### **Imports**
# diffusion policy import
from typing import Tuple, Sequence, Dict, Union, Optional
import numpy as np
import math
import torch
import torch.nn as nn
import collections
import zarr
from diffusers.schedulers.scheduling_ddpm import DDPMScheduler
from diffusers.training_utils import EMAModel
from diffusers.optimization import get_scheduler
from tqdm.auto import tqdm

# logging import
from log_utils import CustomSingletonLogger

# env import
import pygame
import pymunk
import pymunk.pygame_util
from pymunk.space_debug_draw_options import SpaceDebugColor
from pymunk.vec2d import Vec2d
import shapely.geometry as sg
import cv2
import skimage.transform as st
from skvideo.io import vwrite
from IPython.display import Video
import gdown
import os

import gymnasium as gym
try:
    import gym_pusht  # registers "gym_pusht/PushT-v0"
except Exception:
    raise RuntimeError("gym-pusht not installed. Run: pip install gymnasium gym-pusht")

#@markdown ### **Environment**
#@markdown Defines a PyMunk-based Push-T environment `PushTEnv`.
#@markdown
#@markdown **Goal**: push the gray T-block into the green area.
#@markdown
#@markdown Adapted from [Implicit Behavior Cloning](https://implicitbc.github.io/)

class PushTEnvAPI(gym.Env):
    """
    NOTE(Faraz): GPT wrote this Wrapper around the Gymnasium API to work as a 
    drop in replacement for the one originally defined in the Push-T colab statebased notebook.

    Drop-in replacement for the PyMunk PushTEnv.
    Preserves:
      - obs: [agent_x, agent_y, block_x, block_y, block_angle]
      - action scale your policy expects: absolute targets in [0, 512]^2
      - API: reset() -> (obs, info), step(action) -> (obs, reward, terminated, truncated, info)
      - action_space / observation_space attributes (so .sample() etc. work)
    """
    metadata = {"render_modes": ["human", "rgb_array"], "video.frames_per_second": 10}
    reward_range = (0., 1.)

    def __init__(self, render_size=96, render_mode=None, seed_val=None):
        self.render_size = render_size
        self._seed = seed_val
        self.render_mode = render_mode

        # Use STATE obs for speed; pixels only for rendering (lazy).
        self._env = gym.make(
            "gym_pusht/PushT-v0", 
            obs_type="state", 
            render_mode=self.render_mode
        )
        self._act_low = self._env.action_space.low
        self._act_high = self._env.action_space.high

        # ---- Define Gym spaces to match your original env ----
        ws = 512
        self.observation_space = gym.spaces.Box(
            low=np.array([0, 0, 0, 0, 0], dtype=np.float64),
            high=np.array([ws, ws, ws, ws, np.pi * 2], dtype=np.float64),
            shape=(5,),
            dtype=np.float64,
        )
        self.action_space = gym.spaces.Box(
            low=np.array([0, 0], dtype=np.float32),
            high=np.array([ws, ws], dtype=np.float32),
            shape=(2,),
            dtype=np.float32,
        )

    # keep your old API
    def seed(self, seed=None):
        if seed is None:
            seed = int(np.random.randint(0, 25536))
        self._seed = seed
        try:
            self._env.reset(seed=seed)
        except TypeError:
            pass

    def _obs_to_vec(self, obs):
        # gym-pusht state: dict('agent_pos': (2,), 'block_pose': (3, [x,y,theta]))
        if isinstance(obs, dict) and "agent_pos" in obs and "block_pose" in obs:
            ax, ay = obs["agent_pos"]
            bx, by, th = obs["block_pose"]
            return np.array([ax, ay, bx, by, th], dtype=np.float64)
        arr = np.asarray(obs, dtype=np.float64).reshape(-1)
        if arr.shape[0] < 5:
            raise ValueError(f"Unexpected obs shape: {arr.shape}")
        return arr[:5]

    def reset(self, *, seed=None, options=None):
        if seed is not None:
            self.seed(seed)
        obs, info = self._env.reset(seed=self._seed)
        return self._obs_to_vec(obs), info

    def _scale_action(self, action):
        """
        Your policy outputs absolute cursor targets in [0,512]^2.
        Map to the wrapped env Box(low, high).
        """
        a = np.asarray(action, dtype=np.float32)
        low, high = self._act_low, self._act_high
        # Common cases
        if np.allclose(low, 0) and np.allclose(high, 1):
            return a / 512.0
        if np.allclose(low, 0) and np.allclose(high, 512):
            return a
        # Generic affine map from [0,512] -> [low, high]
        return (a / 512.0) * (high - low) + low

    def step(self, action):
        act = self._scale_action(action)
        obs, reward, terminated, truncated, info = self._env.step(act)
        return self._obs_to_vec(obs), float(reward), bool(terminated), bool(truncated), info

    def render(self, mode="rgb_array"):
        if self.render_mode is None:
            raise RuntimeError("This env was created headless. Recreate with render_mode='rgb_array'.")
        frame = self._env.render()  # frame matches current state (single env)
        import cv2
        return cv2.resize(frame, (self.render_size, self.render_size))

    def close(self):
        try: self._env.close()
        except Exception: pass


from functools import partial
import numpy as np
import gymnasium as gym

def evaluate_policy_vectorized(
    make_env_fn,                     # callable -> env (e.g., partial(PushTEnvAPI))
    n_envs: int = 16,
    seeds: Optional[Sequence[int]] = None,
    max_steps: int = 200,
    obs_horizon: int = 2,
    pred_horizon: int = 16,
    action_horizon: int = 8,
    stats=None,                      # your dataset.stats
    device=None,                     # your torch device
    policy=None
):
    """
    NOTE(faraz): written entirely by GPT

    Runs one episode per env (up to max_steps), no rendering (fast).
    Returns: dict(success_rate, avg_return, returns, successes)
    """
    assert stats is not None and device is not None

    # ----- Build vectorized envs with distinct seeds -----
    if seeds is None:
        seeds = np.arange(100000, 100000 + n_envs)  # deterministic default
    assert len(seeds) == n_envs

    def make_one(seed):
        def thunk():
            env = make_env_fn()
            env.seed(int(seed))
            return env
        return thunk

    venv = gym.vector.AsyncVectorEnv([make_one(s) for s in seeds])

    # ----- Reset -----
    obs, infos = venv.reset()
    # obs: (n_envs, 5)
    # Build history buffer: (n_envs, obs_horizon, obs_dim)
    obs_dim = obs.shape[-1]
    obs_hist = np.repeat(obs[:, None, :], obs_horizon, axis=1)

    # Per-env accounting
    # Instead of accumulating returns, keep track of max reward per env
    max_rewards = np.full(n_envs, -np.inf, dtype=np.float32)
    successes = np.zeros(n_envs, dtype=bool)
    dones_mask = np.zeros(n_envs, dtype=bool)

    step_count = 0
    # We'll loop until all envs done or step budget exceeded
    with tqdm(total=max_steps, desc="Parallel EnvAPI Eval", leave=False) as pbar:
        while (not np.all(dones_mask)) and (step_count < max_steps):
            
            # --------- Batch diffusion inference (B = n_envs) ---------
            # Normalize observations using your dataset stats 
            # NOTE (faraz): this is just GPT duplicating the `normalize_data` function I should replace with the actual function later
            nobs = (obs_hist - stats['obs']['min']) / (stats['obs']['max'] - stats['obs']['min'])
            nobs = nobs * 2 - 1  # to [-1, 1]
            nobs_t = torch.from_numpy(nobs).to(device, dtype=torch.float32)  # (B, H, D)
            
            naction = policy.sample(nobs_t, pred_horizon, device)
              
            # Unnormalize actions back to env's absolute [0, 512]^2
            naction_np = naction.detach().to('cpu').numpy()             # (B, T, 2)
            action_pred = ( (naction_np + 1)/2 ) * (stats['action']['max'] - stats['action']['min']) + stats['action']['min']

            # We'll apply only action_horizon steps without replanning (to match your single-env eval)
            start = obs_horizon - 1
            end = start + action_horizon
            action_chunk = action_pred[:, start:end, :]                 # (B, action_horizon, 2)

            # --------- Execute the chunk on the vector env ---------
            for t in range(action_chunk.shape[1]):
                # For done envs, feed a neutral action (ignored by many envs).
                acts = action_chunk[:, t, :]
                # If some envs are already done, avoid stepping them further
                if np.any(dones_mask):
                    acts = acts.copy()
                    acts[dones_mask] = 0.0

                next_obs, reward, terminated, truncated, info = venv.step(acts)

                # Update max reward for active envs
                active = ~dones_mask
                # Only update max_rewards for active envs
                max_rewards[active] = np.maximum(max_rewards[active], reward[active].astype(np.float32))

                # Mark success using "terminated" (task complete). "truncated" is timeout.
                newly_done = (terminated | truncated) & ~dones_mask
                successes[newly_done] = terminated[newly_done]
                dones_mask |= (terminated | truncated)

                # Maintain the obs history for active envs
                # Shift obs_hist left and append new observation for active envs
                obs_hist[active, :-1, :] = obs_hist[active, 1:, :]
                obs_hist[active, -1, :] = next_obs[active]

                obs = next_obs
                step_count += 1
                
                # Update progress bar
                pbar.update(1)
                pbar.set_postfix({
                    'step': step_count,
                    'done_envs': np.sum(dones_mask),
                    'avg_reward': f"{np.mean(max_rewards[active]):.2f}" if np.any(active) else "N/A"
                })

                # Early exit if all envs finished
                if np.all(dones_mask) or step_count >= max_steps:
                    break

    venv.close()

    # Print scores for every env
    print("Scores for each environment (max reward over all timesteps):")
    for i, score in enumerate(max_rewards):
        print(f"Env {i}: {score:.2f}")

    return {
        "success_rate": float(successes.mean()),
        "avg_return": float(max_rewards.mean()),
        "returns": max_rewards,
        "successes": successes,
    }

def env_demo():
    # from huggingface_hub.utils import IGNORE_GIT_FOLDER_PATTERNS
    #@markdown ### **Env Demo**
    #@markdown Standard Gym Env (0.21.0 API)

    # 0. create env object
    env = PushTEnvAPI()

    # 1. seed env for initial state.
    # Seed 0-200 are used for the demonstration dataset.
    env.seed(1000)

    # 2. must reset before use
    # obs, IGNORE_GIT_FOLDER_PATTERNS = env.reset()
    obs, _ = env.reset()

    # 3. 2D positional action space [0,512]
    action = env.action_space.sample()

    # 4. Standard gym step method
    obs, reward, terminated, truncated, info = env.step(action)

    # prints and explains each dimension of the observation and action vectors
    with np.printoptions(precision=4, suppress=True, threshold=5):
        print("Obs: ", repr(obs))
        print("Obs:        [agent_x,  agent_y,  block_x,  block_y,    block_angle]")
        print("Action: ", repr(action))
        print("Action:   [target_agent_x, target_agent_y]")
    
    return env

#@markdown ### **Dataset**
#@markdown
#@markdown Defines `PushTStateDataset` and helper functions
#@markdown
#@markdown The dataset class
#@markdown - Load data (obs, action) from a zarr storage
#@markdown - Normalizes each dimension of obs and action to [-1,1]
#@markdown - Returns
#@markdown  - All possible segments with length `pred_horizon`
#@markdown  - Pads the beginning and the end of each episode with repetition
#@markdown  - key `obs`: shape (obs_horizon, obs_dim)
#@markdown  - key `action`: shape (pred_horizon, action_dim)

def create_sample_indices(
        episode_ends:np.ndarray, sequence_length:int,
        pad_before: int=0, pad_after: int=0):
    indices = list()
    for i in range(len(episode_ends)):
        start_idx = 0
        if i > 0:
            start_idx = episode_ends[i-1]
        end_idx = episode_ends[i]
        episode_length = end_idx - start_idx

        min_start = -pad_before
        max_start = episode_length - sequence_length + pad_after

        # range stops one idx before end
        for idx in range(min_start, max_start+1):
            buffer_start_idx = max(idx, 0) + start_idx
            buffer_end_idx = min(idx+sequence_length, episode_length) + start_idx
            start_offset = buffer_start_idx - (idx+start_idx)
            end_offset = (idx+sequence_length+start_idx) - buffer_end_idx
            sample_start_idx = 0 + start_offset
            sample_end_idx = sequence_length - end_offset
            indices.append([
                buffer_start_idx, buffer_end_idx,
                sample_start_idx, sample_end_idx])
    indices = np.array(indices)
    return indices


def sample_sequence(train_data, sequence_length,
                    buffer_start_idx, buffer_end_idx,
                    sample_start_idx, sample_end_idx):
    result = dict()
    for key, input_arr in train_data.items():
        sample = input_arr[buffer_start_idx:buffer_end_idx]
        data = sample
        if (sample_start_idx > 0) or (sample_end_idx < sequence_length):
            data = np.zeros(
                shape=(sequence_length,) + input_arr.shape[1:],
                dtype=input_arr.dtype)
            if sample_start_idx > 0:
                data[:sample_start_idx] = sample[0]
            if sample_end_idx < sequence_length:
                data[sample_end_idx:] = sample[-1]
            data[sample_start_idx:sample_end_idx] = sample
        result[key] = data
    return result

# normalize data
def get_data_stats(data):
    data = data.reshape(-1,data.shape[-1])
    stats = {
        'min': np.min(data, axis=0),
        'max': np.max(data, axis=0)
    }
    return stats

def normalize_data(data, stats):
    # nomalize to [0,1]
    ndata = (data - stats['min']) / (stats['max'] - stats['min'])
    # normalize to [-1, 1]
    ndata = ndata * 2 - 1
    return ndata

def unnormalize_data(ndata, stats):
    ndata = (ndata + 1) / 2
    data = ndata * (stats['max'] - stats['min']) + stats['min']
    return data


# dataset
class PushTStateDataset(torch.utils.data.Dataset):
    def __init__(self, dataset_path,
                 pred_horizon, obs_horizon, action_horizon):

        # read from zarr dataset
        dataset_root = zarr.open(dataset_path, 'r')
        # All demonstration episodes are concatinated in the first dimension N
        train_data = {
            # (N, action_dim)
            'action': dataset_root['data']['action'][:],
            # (N, obs_dim)
            'obs': dataset_root['data']['state'][:]
        }
        # Marks one-past the last index for each episode
        episode_ends = dataset_root['meta']['episode_ends'][:]

        # compute start and end of each state-action sequence
        # also handles padding
        indices = create_sample_indices(
            episode_ends=episode_ends,
            sequence_length=pred_horizon,
            # add padding such that each timestep in the dataset are seen
            pad_before=obs_horizon-1,
            pad_after=action_horizon-1)

        # compute statistics and normalized data to [-1,1]
        stats = dict()
        normalized_train_data = dict()
        for key, data in train_data.items():
            stats[key] = get_data_stats(data)
            normalized_train_data[key] = normalize_data(data, stats[key])

        self.indices = indices
        self.stats = stats
        self.normalized_train_data = normalized_train_data
        self.pred_horizon = pred_horizon
        self.action_horizon = action_horizon
        self.obs_horizon = obs_horizon

    def __len__(self):
        # all possible segments of the dataset
        return len(self.indices)

    def __getitem__(self, idx):
        # get the start/end indices for this datapoint
        buffer_start_idx, buffer_end_idx, \
            sample_start_idx, sample_end_idx = self.indices[idx]

        # get nomralized data using these indices
        nsample = sample_sequence(
            train_data=self.normalized_train_data,
            sequence_length=self.pred_horizon,
            buffer_start_idx=buffer_start_idx,
            buffer_end_idx=buffer_end_idx,
            sample_start_idx=sample_start_idx,
            sample_end_idx=sample_end_idx
        )

        # discard unused observations
        nsample['obs'] = nsample['obs'][:self.obs_horizon,:]
        return nsample

def dataset_demo(batch_size=256, pred_horizon=16, obs_horizon=2, action_horizon=8):
    #@markdown ### **Dataset Demo**

    # download demonstration data from Google Drive
    dataset_path = "pusht_cchi_v7_replay.zarr.zip"
    if not os.path.isfile(dataset_path):
        id = "1KY1InLurpMvJDRb14L9NlXT_fEsCvVUq&confirm=t"
        gdown.download(id=id, output=dataset_path, quiet=False)

    # parameters
    #|o|o|                             observations: 2
    #| |a|a|a|a|a|a|a|a|               actions executed: 8
    #|p|p|p|p|p|p|p|p|p|p|p|p|p|p|p|p| actions predicted: 16

    # create dataset from file
    dataset = PushTStateDataset(
        dataset_path=dataset_path,
        pred_horizon=pred_horizon,
        obs_horizon=obs_horizon,
        action_horizon=action_horizon
    )
    # save training data statistics (min, max) for each dim
    stats = dataset.stats

    # create dataloader
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=batch_size,
        num_workers=1,
        shuffle=True,
        # accelerate cpu-gpu transfer
        pin_memory=True,
        # don't kill worker process afte each epoch
        persistent_workers=True
    )

    # visualize data in batch
    batch = next(iter(dataloader))
    print("batch['obs'].shape:", batch['obs'].shape)
    print("batch['action'].shape", batch['action'].shape)

    return dataloader, stats


#@markdown ### **Network**
#@markdown
#@markdown Defines a 1D UNet architecture `ConditionalUnet1D`
#@markdown as the noies prediction network
#@markdown
#@markdown Components
#@markdown - `SinusoidalPosEmb` Positional encoding for the diffusion iteration k
#@markdown - `Downsample1d` Strided convolution to reduce temporal resolution
#@markdown - `Upsample1d` Transposed convolution to increase temporal resolution
#@markdown - `Conv1dBlock` Conv1d --> GroupNorm --> Mish
#@markdown - `ConditionalResidualBlock1D` Takes two inputs `x` and `cond`. \
#@markdown `x` is passed through 2 `Conv1dBlock` stacked together with residual connection.
#@markdown `cond` is applied to `x` with [FiLM](https://arxiv.org/abs/1709.07871) conditioning.

class SinusoidalPosEmb(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, x):
        device = x.device
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)
        emb = x[:, None] * emb[None, :]
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)
        return emb


class Downsample1d(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.conv = nn.Conv1d(dim, dim, 3, 2, 1)

    def forward(self, x):
        return self.conv(x)

class Upsample1d(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.conv = nn.ConvTranspose1d(dim, dim, 4, 2, 1)

    def forward(self, x):
        return self.conv(x)


class Conv1dBlock(nn.Module):
    '''
        Conv1d --> GroupNorm --> Mish
    '''

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),
            nn.GroupNorm(n_groups, out_channels),
            nn.Mish(),
        )

    def forward(self, x):
        return self.block(x)


class ConditionalResidualBlock1D(nn.Module):
    def __init__(self,
            in_channels,
            out_channels,
            cond_dim,
            kernel_size=3,
            n_groups=8):
        super().__init__()

        self.blocks = nn.ModuleList([
            Conv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups),
            Conv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups),
        ])

        # FiLM modulation https://arxiv.org/abs/1709.07871
        # predicts per-channel scale and bias
        cond_channels = out_channels * 2
        self.out_channels = out_channels
        self.cond_encoder = nn.Sequential(
            nn.Mish(),
            nn.Linear(cond_dim, cond_channels),
            nn.Unflatten(-1, (-1, 1))
        )

        # make sure dimensions compatible
        self.residual_conv = nn.Conv1d(in_channels, out_channels, 1) \
            if in_channels != out_channels else nn.Identity()

    def forward(self, x, cond):
        '''
            x : [ batch_size x in_channels x horizon ]
            cond : [ batch_size x cond_dim]

            returns:
            out : [ batch_size x out_channels x horizon ]
        '''
        out = self.blocks[0](x)
        embed = self.cond_encoder(cond)

        embed = embed.reshape(
            embed.shape[0], 2, self.out_channels, 1)
        scale = embed[:,0,...]
        bias = embed[:,1,...]
        out = scale * out + bias

        out = self.blocks[1](out)
        out = out + self.residual_conv(x)
        return out


class ConditionalUnet1D(nn.Module):
    def __init__(self,
        input_dim,
        global_cond_dim,
        diffusion_step_embed_dim=256,
        down_dims=[256,512,1024],
        kernel_size=5,
        n_groups=8
        ):
        """
        input_dim: Dim of actions.
        global_cond_dim: Dim of global conditioning applied with FiLM
          in addition to diffusion step embedding. This is usually obs_horizon * obs_dim
        diffusion_step_embed_dim: Size of positional encoding for diffusion iteration k
        down_dims: Channel size for each UNet level.
          The length of this array determines numebr of levels.
        kernel_size: Conv kernel size
        n_groups: Number of groups for GroupNorm
        """

        super().__init__()
        all_dims = [input_dim] + list(down_dims)
        start_dim = down_dims[0]

        dsed = diffusion_step_embed_dim
        diffusion_step_encoder = nn.Sequential(
            SinusoidalPosEmb(dsed),
            nn.Linear(dsed, dsed * 4),
            nn.Mish(),
            nn.Linear(dsed * 4, dsed),
        )
        cond_dim = dsed + global_cond_dim

        in_out = list(zip(all_dims[:-1], all_dims[1:]))
        mid_dim = all_dims[-1]
        self.mid_modules = nn.ModuleList([
            ConditionalResidualBlock1D(
                mid_dim, mid_dim, cond_dim=cond_dim,
                kernel_size=kernel_size, n_groups=n_groups
            ),
            ConditionalResidualBlock1D(
                mid_dim, mid_dim, cond_dim=cond_dim,
                kernel_size=kernel_size, n_groups=n_groups
            ),
        ])

        down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            down_modules.append(nn.ModuleList([
                ConditionalResidualBlock1D(
                    dim_in, dim_out, cond_dim=cond_dim,
                    kernel_size=kernel_size, n_groups=n_groups),
                ConditionalResidualBlock1D(
                    dim_out, dim_out, cond_dim=cond_dim,
                    kernel_size=kernel_size, n_groups=n_groups),
                Downsample1d(dim_out) if not is_last else nn.Identity()
            ]))

        up_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            up_modules.append(nn.ModuleList([
                ConditionalResidualBlock1D(
                    dim_out*2, dim_in, cond_dim=cond_dim,
                    kernel_size=kernel_size, n_groups=n_groups),
                ConditionalResidualBlock1D(
                    dim_in, dim_in, cond_dim=cond_dim,
                    kernel_size=kernel_size, n_groups=n_groups),
                Upsample1d(dim_in) if not is_last else nn.Identity()
            ]))

        final_conv = nn.Sequential(
            Conv1dBlock(start_dim, start_dim, kernel_size=kernel_size),
            nn.Conv1d(start_dim, input_dim, 1),
        )

        self.diffusion_step_encoder = diffusion_step_encoder
        self.up_modules = up_modules
        self.down_modules = down_modules
        self.final_conv = final_conv

        print("number of parameters: {:e}".format(
            sum(p.numel() for p in self.parameters()))
        )

    def forward(self,
            sample: torch.Tensor,
            timestep: Union[torch.Tensor, float, int],
            global_cond=None):
        """
        x: (B,T,input_dim)
        timestep: (B,) or int, diffusion step
        global_cond: (B,global_cond_dim)
        output: (B,T,input_dim)
        """
        # (B,T,C)
        sample = sample.moveaxis(-1,-2)
        # (B,C,T)

        # 1. time
        timesteps = timestep
        if not torch.is_tensor(timesteps):
            # TODO: this requires sync between CPU and GPU. So try to pass timesteps as tensors if you can
            timesteps = torch.tensor([timesteps], dtype=torch.long, device=sample.device)
        elif torch.is_tensor(timesteps) and len(timesteps.shape) == 0:
            timesteps = timesteps[None].to(sample.device)
        # broadcast to batch dimension in a way that's compatible with ONNX/Core ML
        timesteps = timesteps.expand(sample.shape[0])

        global_feature = self.diffusion_step_encoder(timesteps)

        if global_cond is not None:
            global_feature = torch.cat([
                global_feature, global_cond
            ], axis=-1)

        x = sample
        h = []
        for idx, (resnet, resnet2, downsample) in enumerate(self.down_modules):
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            h.append(x)
            x = downsample(x)

        for mid_module in self.mid_modules:
            x = mid_module(x, global_feature)

        for idx, (resnet, resnet2, upsample) in enumerate(self.up_modules):
            x = torch.cat((x, h.pop()), dim=1)
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)

        x = self.final_conv(x)

        # (B,C,T)
        x = x.moveaxis(-1,-2)
        # (B,T,C)
        return x

class StateBasedDiffusionPolicy(nn.Module):

    def __init__(self, action_dim, obs_dim, obs_horizon, num_diffusion_iters):
        super().__init__()
        
        self.noise_pred_net = ConditionalUnet1D(
            input_dim=action_dim,
            global_cond_dim=obs_dim*obs_horizon
        )

        self.noise_scheduler = DDPMScheduler(
            num_train_timesteps=num_diffusion_iters,
            # the choise of beta schedule has big impact on performance
            # we found squared cosine works the best
            beta_schedule='squaredcos_cap_v2',
            # clip output to [-1,1] to improve stability
            clip_sample=True,
            # our network predicts noise (instead of denoised action)
            prediction_type='epsilon'
        )

    def forward(self, nobs, naction, device):
        B = nobs.shape[0]

        # observation as FiLM conditioning
        # (B, obs_horizon * obs_dim)
        obs_cond = nobs
        obs_cond = obs_cond.flatten(start_dim=1)

        # sample noise to add to actions
        noise = torch.randn(naction.shape, device=device)

        # sample a diffusion iteration for each data point
        timesteps = torch.randint(
            0, self.noise_scheduler.config.num_train_timesteps,
            (B,), device=device
        ).long()

        # add noise to the clean images according to the noise magnitude at each diffusion iteration
        # (this is the forward diffusion process)
        noisy_actions = self.noise_scheduler.add_noise(
            naction, noise, timesteps)

        # predict the noise residual
        noise_pred = self.noise_pred_net(
            noisy_actions, timesteps, global_cond=obs_cond)

        # L2 loss
        loss = nn.functional.mse_loss(noise_pred, noise)
        return loss

    def sample(self, nobs_t, pred_horizon, device):
        B = nobs_t.shape[0]
        obs_cond = nobs_t.flatten(start_dim=1)  # (B, H*D)

        # Generate an action sequence for each obs
        with torch.no_grad():
            noisy_action = torch.randn((B, pred_horizon, 2), device=device)
            naction = noisy_action
            self.noise_scheduler.set_timesteps(self.noise_scheduler.config.num_train_timesteps)
            for k in self.noise_scheduler.timesteps:
                noise_pred = self.noise_pred_net(naction, k, global_cond=obs_cond)
                naction = self.noise_scheduler.step(model_output=noise_pred, timestep=k, sample=naction).prev_sample

        return naction

class SingleStepStateBasedDiscreteDiffusionPolicy(nn.Module):

    def __init__(self, action_dim, vocab_size, embed_dim, obs_dim, obs_horizon):
        super().__init__()

        self.num_timesteps = 1
        self.action_dim = action_dim

        self.action_pred_net = ConditionalUnet1D(
            input_dim=embed_dim,
            global_cond_dim=obs_dim*obs_horizon
        )

        # initialize tokenizer
        from tokenization import BinningActionTokenizer
        self.tokenizer = BinningActionTokenizer(
            max_action_dim=action_dim,
            action_chunk_size=16,
            vocab_size=vocab_size,
            contiguous_dimensions=False
        )

        # initialize embedding
        self.token_embedding = nn.Embedding(vocab_size, embed_dim)

    @staticmethod
    def sample_categorical(probs):
        shape = probs.shape[:-1]
        probs_flat = probs.reshape(-1, probs.shape[-1])
        samples = torch.multinomial(probs_flat, num_samples=1)  # (N, 1)
        return samples.reshape(*shape)

    def forward(self, nobs, naction, device):
        B = nobs.shape[0]

        # observation as FiLM conditioning
        # (B, obs_horizon * obs_dim)
        obs_cond = nobs
        obs_cond = obs_cond.flatten(start_dim=1)

        naction = self.tokenizer.tokenize(naction)
        noise = torch.full_like(naction, 0, dtype=torch.long, device=device)

        timesteps = torch.full((B,), self.num_timesteps, device=device).long()

        noise_emb = self.token_embedding(noise)
        action_emb_pred = self.action_pred_net(noise_emb, timesteps, global_cond=obs_cond)
        action_pred = (self.token_embedding.weight @ action_emb_pred.transpose(1, 2)).transpose(1, 2)

        loss = torch.nn.functional.cross_entropy(action_pred.permute(0, 2, 1), naction)
        return loss

    def sample(self, nobs_t, pred_horizon, device):
        B = nobs_t.shape[0]
        obs_cond = nobs_t.flatten(start_dim=1)  # (B, H*D)

        # Generate an action sequence for each obs
        with torch.no_grad():
            naction = torch.full((B, pred_horizon * self.action_dim), 0, device=device)

            naction_emb = self.token_embedding(naction)
            action_emb_pred = self.action_pred_net(naction_emb, self.num_timesteps, global_cond=obs_cond)
            action_pred = (self.token_embedding.weight @ action_emb_pred.transpose(1, 2)).transpose(1, 2)  # (B, C, K)

            softmax_logits = torch.softmax(action_pred, dim=-1).detach()
            naction = self.sample_categorical(softmax_logits)

        naction = self.tokenizer.detokenize(naction)
        return naction

class StateBasedDiscreteDiffusionPolicy(nn.Module):
    
    def __init__(self, action_dim, vocab_size, embed_dim, obs_dim, obs_horizon, num_diffusion_iters, tokenizer_name, schedule_name):
        super().__init__()
        
        self.num_timesteps = num_diffusion_iters
        self.action_dim = action_dim

        self.action_pred_net = ConditionalUnet1D(
            input_dim=embed_dim,
            global_cond_dim=obs_dim*obs_horizon
        )

        # initialize tokenizer
        from tokenization import get_tokenizer
        self.tokenizer = get_tokenizer(
            tokenizer_name=tokenizer_name,
            vocab_size=vocab_size,
            max_action_dim=action_dim,
            action_chunk_size=16,
        )

        # initialize embedding
        self.token_embedding = nn.Embedding(vocab_size, embed_dim)

        # initialize schedule
        from schedules import get_schedule
        self.schedule = get_schedule(schedule_name, self.num_timesteps, self.tokenizer.pad_token_id)

    @staticmethod
    def sample_categorical(probs):
        shape = probs.shape[:-1]
        probs_flat = probs.reshape(-1, probs.shape[-1])
        samples = torch.multinomial(probs_flat, num_samples=1)  # (N, 1)
        return samples.reshape(*shape)

    def forward(self, nobs, naction, device):
        B = nobs.shape[0]

        # observation as FiLM conditioning
        # (B, obs_horizon * obs_dim)
        obs_cond = nobs
        obs_cond = obs_cond.flatten(start_dim=1)

        naction = self.tokenizer.tokenize(naction)
        noise = torch.full_like(naction, 0, dtype=torch.long, device=device)

        timesteps = torch.randint(
            0, self.num_timesteps,
            (B,), device=device
        ).long()

        noised_action = self.schedule.noise_tokens(
            naction, noise, 1 - (timesteps.float() / self.num_timesteps)) # 0 -> 1, self.num_timesteps -> 0

        noise_emb = self.token_embedding(noised_action)
        action_emb_pred = self.action_pred_net(noise_emb, timesteps, global_cond=obs_cond)
        action_pred = (self.token_embedding.weight @ action_emb_pred.transpose(1, 2)).transpose(1, 2)

        loss = torch.nn.functional.cross_entropy(action_pred.permute(0, 2, 1), naction)
        return loss

    def sample(self, nobs_t, pred_horizon, device):
        B = nobs_t.shape[0]
        obs_cond = nobs_t.flatten(start_dim=1)  # (B, H*D)

        # Generate an action sequence for each obs
        with torch.no_grad():
            noised_action = torch.full((B, pred_horizon * self.action_dim), 0, device=device)
            naction = noised_action

            timesteps = torch.arange(self.num_timesteps, 0, -1, device=device).long()
            for k in timesteps:
                naction_emb = self.token_embedding(naction)
                action_emb_pred = self.action_pred_net(naction_emb, k, global_cond=obs_cond)
                action_pred = (self.token_embedding.weight @ action_emb_pred.transpose(1, 2)).transpose(1, 2)  # (B, C, K)

                softmax_logits = torch.softmax(action_pred, dim=-1).detach()
                k_schedule = torch.full((B,), (1 - k.float() / self.num_timesteps), device=device)
                naction, _ = self.schedule.step(naction, softmax_logits, k_schedule) # 0 -> 1, self.num_timesteps -> 0
            
            # k = self.num_timesteps
            # while k > 0:
            #     naction_emb = self.token_embedding(naction)
            #     noise_emb_pred = self.noise_pred_net(naction_emb, k, global_cond=obs_cond)
            #     noise_pred = (self.token_embedding.weight @ noise_emb_pred.transpose(1, 2)).transpose(1, 2)  # (B, C, K)

            #     naction, new_k = self.schedule.step(naction, noise_pred, (1 - k / self.num_timesteps)) # 0 -> 1, self.num_timesteps -> 0
            #     k = (1 - new_k) * self.num_timesteps

        naction = self.tokenizer.detokenize(naction)
        return naction
            
def network_demo(policy_name, num_diffusion_iters, tokenizer_name, vocab_size, embed_dim, schedule_name, pred_horizon=16, obs_horizon=2, action_horizon=6):
    #@markdown ### **Network Demo**

    # observation and action dimensions corrsponding to
    # the output of PushTEnv
    obs_dim = 5
    action_dim = 2
    # num_diffusion_iters = 20

    # vocab_size = 20
    # embed_dim = 256
    # schedule_name = "vanilla"

    if policy_name == "continuous":
        policy = StateBasedDiffusionPolicy(action_dim, obs_dim, obs_horizon, num_diffusion_iters)
    elif policy_name == "discrete_singlestep":
        policy = SingleStepStateBasedDiscreteDiffusionPolicy(action_dim, vocab_size, embed_dim, obs_dim, obs_horizon, tokenizer_name)
    elif policy_name == "discrete":
        policy = StateBasedDiscreteDiffusionPolicy(action_dim, vocab_size, embed_dim, obs_dim, obs_horizon, num_diffusion_iters, tokenizer_name, schedule_name)
    else:
        raise ValueError("invalid policy name")

    # example inputs
    noised_action = torch.randn((1, pred_horizon, action_dim))
    noised_action = torch.clamp(noised_action, -1, 1)
    obs = torch.zeros((1, obs_horizon, obs_dim))

    policy.forward(obs, noised_action, obs.device)
    policy.sample(obs, pred_horizon, obs.device)

    diffusion_iter = torch.zeros((1,))

    if policy_name == "continuous":
        pred_net = policy.noise_pred_net
    elif policy_name == "discrete_singlestep" or policy_name == "discrete":
        pred_net = policy.action_pred_net
        noised_action = policy.tokenizer.tokenize(noised_action)
        noised_action = policy.token_embedding(noised_action)

    # the noise prediction network
    # takes noisy action, diffusion iteration and observation as input
    # predicts the noise added to action
    noise = pred_net(
        sample=noised_action,
        timestep=diffusion_iter,
        global_cond=obs.flatten(start_dim=1))

    # illustration of removing noise
    # the actual noise removal is performed by NoiseScheduler
    # and is dependent on the diffusion noise schedule
    denoised_action = noised_action - noise

    return policy


def train(policy, dataloader, stats, num_epochs, load_pretrained=False, pred_horizon=16, obs_horizon=2, action_horizon=8):
    # device transfer
    device = torch.device('cuda')
    policy = policy.to(device)

    #@markdown ### **Training**
    #@markdown
    #@markdown Takes about an hour. If you don't want to wait, skip to the next cell
    #@markdown to load pre-trained weights

    # Initialize logger with wandb enabled for KitchenSink project
    logger = CustomSingletonLogger(use_wandb=True)

    # num_epochs = 200

    # Exponential Moving Average
    # accelerates training and improves stability
    # holds a copy of the model weights
    ema = EMAModel(
        parameters=policy.parameters(),
        power=0.75)

    # Standard ADAM optimizer
    # Note that EMA parametesr are not optimized
    optimizer = torch.optim.AdamW(
        params=policy.parameters(),
        lr=1e-4, weight_decay=1e-6)

    # Cosine LR schedule with linear warmup
    lr_scheduler = get_scheduler(
        name='cosine',
        optimizer=optimizer,
        num_warmup_steps=500,
        num_training_steps=len(dataloader) * num_epochs
    )

    # Initialize global step counter for logging
    global_step = 0
    logger.set_global_step(global_step)

    with tqdm(range(num_epochs), desc='Epoch') as tglobal:
        # epoch loop
        for epoch_idx in tglobal:
            epoch_loss = list()
            # batch loop
            with tqdm(dataloader, desc='Batch', leave=False) as tepoch:
                for nbatch in tepoch:
                    # data normalized in dataset
                    # device transfer
                    nobs = nbatch['obs'].to(device)
                    naction = nbatch['action'].to(device)
                    B = nobs.shape[0]
                    
                    # (B, obs_horizon, obs_dim)
                    nobs = nobs[:,:obs_horizon,:]
                    loss = policy.forward(nobs, naction, device)

                    # optimize
                    loss.backward()
                    optimizer.step()
                    optimizer.zero_grad()
                    # step lr scheduler every batch
                    # this is different from standard pytorch behavior
                    lr_scheduler.step()

                    # update Exponential Moving Average of the model weights
                    ema.step(policy.parameters())

                    # logging
                    loss_cpu = loss.item()
                    epoch_loss.append(loss_cpu)
                    tepoch.set_postfix(loss=loss_cpu)
                    
                    # Log train loss to wandb KitchenSink
                    logger.log_to_wandb_for_current_step({"train_loss": loss_cpu})
                    
                    # Update global step for next iteration
                    global_step += 1
                    logger.set_global_step(global_step)
            tglobal.set_postfix(loss=np.mean(epoch_loss))

            if epoch_idx % 10 == 0:
                
                # Weights of the EMA model
                # is used for inference
                ema_policy = policy
                ema.copy_to(policy.parameters())

                #@markdown ### **Loading Pretrained Checkpoint**
                #@markdown Set `load_pretrained = True` to load pretrained weights.
                if load_pretrained:
                    ckpt_path = "pusht_state_100ep.ckpt"
                    if not os.path.isfile(ckpt_path):
                        id = "1mHDr_DEZSdiGo9yecL50BBQYzR8Fjhl_&confirm=t"
                        gdown.download(id=id, output=ckpt_path, quiet=False)

                    state_dict = torch.load(ckpt_path, map_location='cuda', weights_only=True)
                    ema_policy = policy
                    ema_policy.noise_pred_net.load_state_dict(state_dict)
                    print('Pretrained weights loaded.')
                else:
                    print("Skipped pretrained weight loading.")

                # Vectorized evaluation every 10 epochs (no rendering, fast)
                import time
                n_envs = 16
                seeds = np.arange(100000, 100000 + n_envs)  # or any list of length n_envs

                start_time = time.time()
                metrics = evaluate_policy_vectorized(
                    make_env_fn=partial(PushTEnvAPI, render_size=96),
                    n_envs=n_envs,
                    seeds=seeds,
                    max_steps=200,
                    obs_horizon=obs_horizon,
                    pred_horizon=pred_horizon,
                    action_horizon=action_horizon,
                    stats=stats,
                    device=device,
                    policy=policy
                )
                elapsed_time = time.time() - start_time

                print(f"[Vector Eval] n_envs={n_envs}  success_rate={metrics['success_rate']:.3f}  avg_return={metrics['avg_return']:.2f}")
                print(f"[Vector Eval] Time elapsed: {elapsed_time:.2f} seconds")

                # Optional: log to wandb
                logger.log_to_wandb_for_current_step({
                    "vector_success_rate": metrics["success_rate"],
                    "vector_avg_return": metrics["avg_return"],
                    "vector_eval_time_sec": elapsed_time,
                })

                #@markdown ### **Inference**

                # limit enviornment interaction to 200 steps before termination
                max_steps = 200
                env = PushTEnvAPI(render_mode="rgb_array")
                # use a seed >200 to avoid initial states seen in the training dataset
                env.seed(100000)

                # get first observation
                obs, info = env.reset()

                # keep a queue of last 2 steps of observations
                obs_deque = collections.deque(
                    [obs] * obs_horizon, maxlen=obs_horizon)
                # save visualization and rewards
                imgs = [env.render(mode='rgb_array')]
                rewards = list()
                done = False
                step_idx = 0

                with tqdm(total=max_steps, desc="Eval PushTStateEnv") as pbar:
                    while not done:
                        B = 1
                        # stack the last obs_horizon (2) number of observations
                        obs_seq = np.stack(obs_deque)
                        # normalize observation
                        nobs = normalize_data(obs_seq, stats=stats['obs'])
                        # device transfer
                        nobs = torch.from_numpy(nobs).to(device, dtype=torch.float32)

                        # Batch into singleton batch before passing to policy
                        naction = policy.sample(nobs.unsqueeze(0), pred_horizon, device)

                        # unnormalize action
                        naction = naction.detach().to('cpu').numpy()
                        # (B, pred_horizon, action_dim)
                        naction = naction[0]
                        action_pred = unnormalize_data(naction, stats=stats['action'])

                        # only take action_horizon number of actions
                        start = obs_horizon - 1
                        end = start + action_horizon
                        action = action_pred[start:end,:]
                        # (action_horizon, action_dim)

                        # execute action_horizon number of steps
                        # without replanning
                        for i in range(len(action)):
                            # stepping env
                            obs, reward, done, _, info = env.step(action[i])
                            # save observations
                            obs_deque.append(obs)
                            # and reward/vis
                            rewards.append(reward)
                            imgs.append(env.render(mode='rgb_array'))

                            # update progress bar
                            step_idx += 1
                            pbar.update(1)
                            pbar.set_postfix(reward=reward)
                            if step_idx > max_steps:
                                done = True
                            if done:
                                break

                # print out the maximum target coverage
                print('Score: ', max(rewards))

                # visualize
                from IPython.display import Video
                import os
                import wandb

                # Create output directory if it doesn't exist
                os.makedirs('out', exist_ok=True)

                # Save video to out directory
                video_path = 'out/vis.mp4'
                vwrite(video_path, imgs)

                # Log video to wandb
                logger.log_to_wandb_for_current_step({
                    "evaluation_video": wandb.Video(video_path, fps=10, format="mp4"),
                    "final_score": max(rewards)
                })

                Video(video_path, embed=True, width=256, height=256)


import argparse
def main():
    # Create the argument parser
    parser = argparse.ArgumentParser()

    # Script mode
    parser.add_argument("--mode", type=str, default="train", help="script mode [train]")

    # Training args
    parser.add_argument("--num_epochs", type=int, default=10, help="num training epochs")
    parser.add_argument("--load_pretrained", type=bool, default=False, help="load pretrained weights")

    # Dataset args
    parser.add_argument("--pred_horizon", type=int, default=16, help="num of predicted actions")
    parser.add_argument("--obs_horizon", type=int, default=2, help="num of conditioning observations")
    parser.add_argument("--action_horizon", type=int, default=8, help="num of actual actions")
    parser.add_argument("--batch_size", type=int, default=256, help="dataset batch size")

    # Network args
    parser.add_argument("--policy_name", type=str, default="continuous", help="name of diffusion policy model")
    parser.add_argument("--num_diffusion_iters", type=int, default=100, help="num timesteps for diffusion model")
    parser.add_argument("--tokenizer_name", type=str, default="binning", help="name of discrete diffusion tokenizer")
    parser.add_argument("--vocab_size", type=int, default=10, help="vocab size of tokenizer (e.g. num of bins)")
    parser.add_argument("--embed_dim", type=int, default=256, help="dimension of tokenizer embedding space")
    parser.add_argument("--schedule_name", type=str, default="vanilla", help="name of diffusion schedule")

    # Parse the arguments
    args = parser.parse_args()

    env = env_demo()
    dataloader, stats = dataset_demo(args.batch_size, args.pred_horizon, args.obs_horizon, args.action_horizon)
    policy = network_demo(args.policy_name, args.num_diffusion_iters, args.tokenizer_name, args.vocab_size, args.embed_dim, args.schedule_name, args.pred_horizon, args.obs_horizon, args.action_horizon)

    if args.mode == "train":
        assert (args.policy_name == "continuous" or args.load_pretrained == False)
        print(args.policy_name, args.num_diffusion_iters, args.num_epochs, args.vocab_size, args.schedule_name, args.batch_size)
        train(policy, dataloader, stats, args.num_epochs, args.load_pretrained, args.pred_horizon, args.obs_horizon, args.action_horizon)

if __name__ == "__main__":
    main()